name: Build and Release
on: push
jobs:
  build:
    name: Build on macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk --release
  release:
    name: Release
    runs-on: macos-latest
    needs: build
    steps:
      - name: Create a Release APK
      - uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: build/app/outputs/apk/release/app-release.apk
